[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#1c1c1e"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor =  "#1c1c1e" 

# Color used for almost all text.
textColor = "#fefefe" # "#FFFFFF" # "#fafafa"  "#0000FF"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "serif" # "cursive"   # "verdana"
