[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#FFFFFF" # "#454545" # "#ECF0F1"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor =  "#4D4B48"

# Color used for almost all text.
textColor = "#fafafa" # "#000080" "#0000FF"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "serif" # "cursive"   # "verdana"
